#/*==============================================================================
#修订历史
#问题单号          修改人      日期         原因
#==============================================================================*/
obj-$(CONFIG_PANEL_GENERIC_DPI) += panel-generic-dpi.o
obj-$(CONFIG_PANEL_LGPHILIPS_LB035Q02) += panel-lgphilips-lb035q02.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_NEC_NL8048HL11_01B) += panel-nec-nl8048hl11-01b.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
#obj-$(CONFIG_PANEL_HUAWEI) += panel-huawei.o 
obj-$(CONFIG_PANEL_SP_HUAWEI) += panel-samsung-s6e39a.o
obj-$(CONFIG_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o
obj-$(CONFIG_PANEL_ACX565AKM) += panel-acx565akm.o

obj-$(CONFIG_PANEL_TC358765) += panel-tc358765.o
obj-$(CONFIG_PANEL_TOSHIBA_MDV20) += panel-toshiba-mdv20.o
#/*  Reason: lcd-compatible  */
obj-$(CONFIG_PANEL_DETECT) += panel_detect.o

obj-$(CONFIG_PANEL_DETECT) += panel_detect.o
obj-$(CONFIG_LCDD) += lcdd.o
